# opensecurity/templates/initial-admin-password-secret.yaml
{{- /*
Create a secret containing a default initial password.
This is often used by a post-install job to configure OpenSearch security initially.
Ensure this default password is changed or managed securely post-installation.
*/}}
apiVersion: v1
kind: Secret
metadata:
  # Use the chart's fullname helper for consistent naming
  name: {{ include "opensecurity.fullname" . }}-initial-admin-password
  labels:
    # Include standard Helm labels from _helpers.tpl
    {{- include "opensecurity.labels" . | nindent 4 }}
    # Add specific labels if needed for selection/identification
    app.kubernetes.io/component: initial-credentials
  # Add annotations if necessary (e.g., Helm hooks)
  # annotations:
  #   "helm.sh/hook": post-install # Consider if this should be created only on first install
  #   "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  # The key name your post-install-job expects for the admin password.
  # Common keys might be 'password', 'admin-password', or 'ADMIN_PASSWORD'. Adjust if needed.
  # Using a fixed default password. CHANGE THIS IN A PRODUCTION ENVIRONMENT.
  password: "password"
  # You could optionally include the default admin username if the job needs it
  # username: "admin"

{{- /*
  --- Explanatory Comment Removed ---
  The example showing how to use 'include' with values.yaml was removed
  to prevent Helm parsing errors within comments.
  --- End Explanatory Comment Removed ---
*/}}
