apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensecurity.fullname" . }}-initial-admin-password
  labels:
    {{- include "opensecurity.labels" . | nindent 4 }}
    app.kubernetes.io/component: initial-credentials
type: Opaque
stringData:
  password: {{ randAlphaNum 20 | quote }}
