{{- if eq .Values.opensecurity.compliance true }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-report-worker
---
apiVersion: v1
kind: Secret
metadata:
  name: compliance-report-worker-secret
  annotations:
    kubernetes.io/service-account.name: compliance-report-worker
type: kubernetes.io/service-account-token
{{- end }}