apiVersion: v2
name: opencomply
description: |
    ## First Public Release of Opencomply


    Introducing Opencomply’s first public release, designed to centralize asset visibility and enable comprehensive compliance audits across your landscape.


    ### Key Highlights


    - **Centralized Asset Repository**

      - Discover and manage assets from 800+ tables across multiple platforms, including AWS, Azure, EntraID, Google Workspace, GitHub, Cloudflare, DigitalOcean, and Linode.


    - **Integrations**

      - Out-of-the-box connections to leading platforms, categorized as:

        - **Cloud Infrastructure:** AWS, Azure, DigitalOcean, Akamai, Linode

        - **Identity Providers:** Google Workspace, EntraID/Azure

        - **DevOps:** GitHub

        - **AI Platforms:** OpenAI, Cohere  
      - [View all Integrations](https://opencomply.io/compliance/frameworks)

    - **Built-In Compliance Frameworks & Audits**

      - Predefined frameworks including SOC2, HIPAA, GDPR, and NIST CSF.

      - **45+ Out-of-the-Box Compliance Frameworks** for quick, customizable compliance setups.
      
    - **Auditable Frameworks in YAML**

      - Manage compliance frameworks, controls, and policies in Git for version control and auditing.

    ### Fixes & Improvements

    - **Simplified Setup:** Helm-based installation with sample data.
    - **Security, Access & Performance:** Added OIDC SSO support, role-based controls, and enhanced asset discovery.
    - **Documentation & Onboarding:** Improved setup guides and best practices for integrating compliance audits.

    For more details, check out our [documentation](https://opencomply.io/documentation).


# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.0.0"

dependencies:
  - name: keda
    version: 2.15.1
    condition: keda.enabled
  - name: postgresql
    version: 15.5.21
    condition: postgresql.enabled
  - name: opensearch
    version: 2.22.0
    condition: opensearch.enabled
  - name: opensearch-dashboards
    version: 2.20.0
    condition: opensearch-dashboards.enabled

