apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkup-worker
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: checkup-worker
spec:
  minReadySeconds: 10
  {{- if eq .Values.keda.enabled true }}
  replicas: 0
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: checkup-worker
  template:
    metadata:
      labels:
        app: checkup-worker
    spec:
      serviceAccountName: checkup-worker
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: opencomply-node
                    operator: In
                    values:
                      - worker
      containers:
        - name: checkup-worker
          image: "{{ .Values.opensecurity.docker.registry }}/checkup-job:{{ .Values.opensecurity.docker.tags.checkupJob }}"
          command: ["/checkup-job"]
          args:
            - --id=$(WORKER_ID)
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 100Mi
          env:
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"

            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROMETHEUS_PUSH_ADDRESS
              value: "prom-system-prometheus-pushgateway.prom-system.svc.cluster.local:9091"
            - name: INTEGRATION_BASE_URL
              value: "http://integration-service.{{ .Release.Namespace }}.svc.cluster.local:8000"
            - name: CORE_BASE_URL
              value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
            - name: AUTH_BASE_URL
              value: "http://auth-service.{{ .Release.Namespace }}.svc.cluster.local:8251"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: JAEGER_SERVICE_NAME
              value: "checkup-worker"
            - name: TELEMETRY_WORKSPACE_ID
              value: "{{ .Release.Namespace }}"
            - name: TELEMETRY_HOSTNAME
              value: "{{ .Values.global.domain }}"
