---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkup-worker
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: checkup-worker-secret
  namespace: {{ .Release.Namespace }}

  annotations:
    kubernetes.io/service-account.name: checkup-worker
type: kubernetes.io/service-account-token
