apiVersion: v1
kind: Service
metadata:
  name: pennywise-server-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: pennywise-server
spec:
  selector:
    app: pennywise-server
  ports:
    - port: 8080
      targetPort: 8080
