{{- if eq .Values.keda.enabled true }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: compliance-worker-scaled-object
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compliance-worker
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 0
  maxReplicaCount: {{ .Values.opengovernance.parallelism.complianceReportJobMaxParallelism}}
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "compliance-runner"
        consumer: "compliance-runner-service"
        lagThreshold: "{{ .Values.opengovernance.parallelism.complianceReportLagThreshold}}"
        useHttps: "false"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: compliance-worker-manual-scaled-object
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compliance-worker-manual
  pollingInterval: 5
  cooldownPeriod:  300
  minReplicaCount: 0
  maxReplicaCount: {{ .Values.opengovernance.parallelism.complianceReportJobMaxParallelism}}
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "compliance-runner"
        consumer: "compliance-runner-manuals-service"
        lagThreshold: "{{ .Values.opengovernance.parallelism.complianceReportLagThreshold}}"
        useHttps: "false"
{{- end }}