{{- if eq .Values.opensecurity.compliance true }}
{{- if eq .Values.keda.enabled true }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: compliance-summarizer-scaled-object
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compliance-summarizer
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 0
  maxReplicaCount: 1
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "compliance-summarizer"
        consumer: "compliance-summarizer-service"
        lagThreshold: "1"
        useHttps: "false"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: compliance-summarizer-manual-scaled-object
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compliance-summarizer-manual
  pollingInterval: 5
  cooldownPeriod:  300
  minReplicaCount: 0
  maxReplicaCount: 1
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "compliance-summarizer"
        consumer: "compliance-summarizer-manuals-service"
        lagThreshold: "1"
        useHttps: "false"
{{- end }}
{{- end }}