{{- if eq .Values.opensecurity.compliance true }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-summarizer
---
apiVersion: v1
kind: Secret
metadata:
  name: compliance-summarizer-secret
  annotations:
    kubernetes.io/service-account.name: compliance-summarizer
type: kubernetes.io/service-account-token
{{- end }}