apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboard-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: onboard-service
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: onboard-service
  template:
    metadata:
      labels:
        app: onboard-service
    spec:
      serviceAccountName: onboard
      containers:
      - name: onboard-service
        image: "{{ .Values.opengovernance.docker.registry }}/onboard-service:{{ .Values.opengovernance.docker.tags.onboard }}"
        command: ["/onboard-service"]
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    cpu: 1000m
        #    memory: 1.5Gi
        #  requests:
        #    cpu: 100m
        #    memory: 500Mi
        env:
        - name: ONBOARD_STEAMPIPE__HOST
          value: steampipe-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: ONBOARD_STEAMPIPE__PORT
          value: "9193"
        - name: ONBOARD_STEAMPIPE__USERNAME
          value: "steampipe"
        - name: ONBOARD_STEAMPIPE__PASSWORD
          value: "abcd"
        - name: ONBOARD_STEAMPIPE__DB
          value: "steampipe"

        - name: ONBOARD_POSTGRES__HOST
          value: "{{ include "postgres.endpoint" . }}"
        - name: ONBOARD_POSTGRES__PORT
          value: "{{ include "postgres.port" . }}"
        - name: ONBOARD_POSTGRES__DB
          value: "onboard"
        - name: ONBOARD_POSTGRES__USERNAME
          value: "onboard_service"
        - name: ONBOARD_POSTGRES__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: onboardServiceUserPassword
        - name: ONBOARD_POSTGRES__SSLMODE
          value: "{{ include "postgres.sslMode" . }}"
        - name: ONBOARD_HTTP__ADDRESS
          value: "0.0.0.0:6251"
        - name: ONBOARD_INVENTORY__BASE_URL
          value: "http://inventory-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
        - name: ONBOARD_DESCRIBE__BASE_URL
          value: "http://describe-scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251"
        - name: ONBOARD_METADATA__BASE_URL
          value: "http://metadata-service.{{ .Release.Namespace }}.svc.cluster.local:6251"

        - name: ONBOARD_VAULT__PROVIDER
          value: {{ .Values.opengovernance.vault.provider }}
        - name: ONBOARD_VAULT__AWS__REGION
          value: {{ .Values.opengovernance.vault.aws.region }}
        - name: ONBOARD_VAULT__AWS__ROLE_ARN
          value: {{ .Values.opengovernance.vault.aws.roleArn }}
        - name: ONBOARD_VAULT__AWS__ACCESS_KEY
          value: {{ .Values.opengovernance.vault.aws.accessKey }}
        - name: ONBOARD_VAULT__AWS__SECRET_KEY
          value: {{ .Values.opengovernance.vault.aws.secretKey }}
        - name: ONBOARD_VAULT__AZURE__BASE_URL
          value: {{ .Values.opengovernance.vault.azure.baseUrl }}
        - name: ONBOARD_VAULT__AZURE__CLIENT_ID
          value: {{ .Values.opengovernance.vault.azure.clientId }}
        - name: ONBOARD_VAULT__AZURE__TENANT_ID
          value: {{ .Values.opengovernance.vault.azure.tenantId }}
        - name: ONBOARD_VAULT__AZURE__CLIENT_SECRET
          value: {{ .Values.opengovernance.vault.azure.clientSecret }}
        - name: ONBOARD_VAULT__HASHICORP__ADDRESS
          value: "http://{{ .Release.Name }}-vault-internal.{{.Release.Namespace}}.svc.cluster.local:8200"
        - name: ONBOARD_VAULT__KEY_ID
          value: {{ .Values.opengovernance.vault.keyID }}

        - name: ONBOARD_MASTER_ACCESS_KEY
          value: {{ .Values.opengovernance.workspace.masterAccessKey }}
        - name: ONBOARD_MASTER_SECRET_KEY
          value: {{ .Values.opengovernance.workspace.masterSecretKey }}
        - name: ONBOARD_JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ONBOARD_JAEGER_SERVICE_NAME
          value: "onboard-service"
        - name: ONBOARD_JAEGER_SAMPLE_RATE
          value: "0.005"
