---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onboard
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.opengovernance.vault.aws.roleArn }}
#    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-onboard
---
apiVersion: v1
kind: Secret
metadata:
  name: onboard-secret
  annotations:
    kubernetes.io/service-account.name: onboard
type: kubernetes.io/service-account-token
