apiVersion: v1
kind: Service
metadata:
  name: onboard-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: onboard-service
    monitoring: kaytu
spec:
  selector:
    app: onboard-service
  ports:
  - name: http
    port: 6251
    targetPort: 6251
