apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0" # Runs after default resources (weight 0)
    # Add hook-delete-policy if you want Helm to clean up successful jobs
    # "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: configuration # Ensure this ServiceAccount exists
      restartPolicy: OnFailure
      # <<< START Init Containers >>>
      initContainers:
        # --- Wait for Dex ---
        - name: wait-for-dex
          image: curlimages/curl:7.85.0 # Lightweight curl image
          env:
            - name: DEX_URL
              # Using Dex telemetry port for readiness check
              value: "http://{{ .Release.Name }}-dex.{{ .Release.Namespace }}.svc.cluster.local:5558/healthz/ready"
          command: ["sh", "-xc"]
          args:
            - |
              echo "InitContainer (post-install): Waiting for Dex at ${DEX_URL}…"
              retries=60; delay=5; count=0 # Increased retries for potentially slower services
              until curl -sf "${DEX_URL}"; do
                count=$((count+1))
                if [ "$count" -ge "$retries" ]; then
                  echo "InitContainer (post-install): Dex unavailable after ${retries} retries – exiting."
                  exit 1
                fi
                echo "InitContainer (post-install): Dex unavailable - sleeping ${delay}s (attempt ${count}/${retries})"
                sleep "${delay}"
              done
              echo "InitContainer (post-install): Dex is ready!"
          resources:
            limits:
              cpu:    "50m"
              memory: "50Mi"
            requests:
              cpu:    "25m"
              memory: "25Mi"
        # --- Wait for Auth Service ---
        - name: wait-for-auth
          image: curlimages/curl:7.85.0
          env:
            - name: AUTH_URL
              # Assuming a readiness/health endpoint on the main service port
              # Adjust path if needed (e.g., /healthz)
              value: "http://auth-service.{{ .Release.Namespace }}.svc.cluster.local:8251/health"
          command: ["sh", "-xc"]
          args:
            - |
              echo "InitContainer (post-install): Waiting for Auth Service at ${AUTH_URL}…"
              retries=60; delay=5; count=0
              until curl -sf "${AUTH_URL}"; do
                count=$((count+1))
                if [ "$count" -ge "$retries" ]; then
                  echo "InitContainer (post-install): Auth Service unavailable after ${retries} retries – exiting."
                  exit 1
                fi
                echo "InitContainer (post-install): Auth Service unavailable - sleeping ${delay}s (attempt ${count}/${retries})"
                sleep "${delay}"
              done
              echo "InitContainer (post-install): Auth Service is ready!"
          resources:
            limits:
              cpu:    "50m"
              memory: "50Mi"
            requests:
              cpu:    "25m"
              memory: "25Mi"
        # --- Wait for Core Service ---
        - name: wait-for-core
          image: curlimages/curl:7.85.0
          env:
            - name: CORE_URL
              # Assuming a readiness/health endpoint on the main service port
              # Adjust path if needed (e.g., /healthz)
              value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251/healthz/ready:"
          command: ["sh", "-xc"]
          args:
            - |
              echo "InitContainer (post-install): Waiting for Core Service at ${CORE_URL}…"
              retries=60; delay=5; count=0
              until curl -sf "${CORE_URL}"; do
                count=$((count+1))
                if [ "$count" -ge "$retries" ]; then
                  echo "InitContainer (post-install): Core Service unavailable after ${retries} retries – exiting."
                  exit 1
                fi
                echo "InitContainer (post-install): Core Service unavailable - sleeping ${delay}s (attempt ${count}/${retries})"
                sleep "${delay}"
              done
              echo "InitContainer (post-install): Core Service is ready!"
          resources:
            limits:
              cpu:    "50m"
              memory: "50Mi"
            requests:
              cpu:    "25m"
              memory: "25Mi"
      # <<< END Init Containers >>>
      containers:
        - name: post-install-configuration
          image: "{{ .Values.opensecurity.docker.registry }}/post-install-job:{{ .Values.opensecurity.docker.tags.postInstallJob }}"
          command: ["/post-install-job"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 4000Mi
            requests:
              cpu: 500m
              memory: 2000Mi
          env:
            # Assumes 'elastic.envs' helper template is defined in _helpers.tpl
            {{- include "elastic.envs" . | indent 12 }}
            # --- PostgreSQL Connection (for Migrator) ---
            - name: POSTGRESQL_HOST
              # Assumes 'postgres.endpoint' helper template exists
              value: "{{ include "postgres.endpoint" . }}"
            - name: POSTGRESQL_PORT
              # Assumes 'postgres.port' helper template exists
              value: "{{ include "postgres.port" . }}"
            - name: POSTGRESQL_DB
              value: "migrator" # Job connects to 'migrator' DB
            - name: POSTGRESQL_USERNAME
              value: "migrator_worker" # Job connects as 'migrator_worker'
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret # Assumes password is in this secret
                  key: migratorServiceUserPassword # Under this key
            - name: POSTGRESQL_SSLMODE
              # Assumes 'postgres.sslMode' helper template exists
              value: "{{ include "postgres.sslMode" . }}"
            # --- Steampipe Connection ---
            - name: STEAMPIPE_HOST
              # Assumes 'cloudql-service' exists
              value: cloudql-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: STEAMPIPE_PORT
              value: "9193"
            - name: STEAMPIPE_DB
              value: "steampipe"
            - name: STEAMPIPE_USERNAME
              value: "steampipe"
            - name: STEAMPIPE_PASSWORD # TODO: Avoid hardcoding passwords
              value: "abcd"
            - name: STEAMPIPE_SSLMODE
              value: "disable"
            # --- Other Config ---
            - name: HTTP_ADDRESS
              value: "0.0.0.0:6251" # Likely internal port for the job itself
            - name: ANALYTICS_GIT_URL
              value: "https://github.com/opengovern/platform-configuration"
            - name: CORE_BASEURL
              value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
            - name: INTEGRATION_BASEURL
              value: "http://integration-service.{{ .Release.Namespace }}.svc.cluster.local:8000"
            - name: GITHUB_TOKEN
              # Reads token from values file - ensure it's set if needed
              value: "{{ .Values.github.token }}"
            - name: PROMETHEUS_PUSH_ADDRESS
              # Assumes prometheus pushgateway exists at this address
              value: "prom-system-prometheus-pushgateway.prom-system.svc.cluster.local:9091"
            - name: IS_MANUAL
              value: "false"
            - name: JAEGER_AGENT_HOST # For tracing
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_SERVICE_NAME
              value: "migrator"
            # --- Dex Defaults (used by job logic?) ---
            - name: DEX_GRPC_ADDRESS
              value: "{{ .Release.Name }}-dex.{{ .Release.Namespace }}.svc.cluster.local:5557" # Use .Release.Name here
            - name: DEFAULT_DEX_USER_ID
              value: "08a8684b-db88-4b73-90a9-3cd1661f5466" # Hardcoded default ID
            - name: DEFAULT_DEX_USER_NAME
              value: "admin" # Hardcoded default user
            - name: DEFAULT_DEX_USER_EMAIL
              value: "admin@clearcompass.so" # Hardcoded default email

            # --- Use password from the initial admin secret ---
            - name: DEFAULT_DEX_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Use the same name generated by initial-admin-password-secret.yaml
                  name: {{ include "opensecurity.fullname" . }}-initial-admin-password
                  # Key within the secret holding the password
                  key: password
            # --- END MODIFIED LINE ---

            # --- Other Context ---
            - name: PLATFORM_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: COMPLIANCE_ENABLED
              value: "{{ .Values.opensecurity.compliance }}"
            - name: CURRENT_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"

          volumeMounts:
            - name: elasticsearch-index-config
              mountPath: /elasticsearch-index-config
            - name: inventory-data-config
              mountPath: /inventory-data-config
            # Mounts for migrator-config
            - name: migrator-config
              mountPath: /core-migration/metadata.json
              subPath: metadata.json
            - name: migrator-config
              mountPath: /core-migration/query_parameters.json
              subPath: query_parameters.json
            - name: migrator-config
              mountPath: /core-migration/chat_prompt.txt
              subPath: chat_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/main_prompt.txt
              subPath: main_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/assets_chat_prompt.txt
              subPath: assets_chat_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/assets_main_prompt.txt
              subPath: assets_main_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/score_chat_prompt.txt
              subPath: score_chat_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/score_main_prompt.txt
              subPath: score_main_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/compliance_chat_prompt.txt
              subPath: compliance_chat_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/compliance_main_prompt.txt
              subPath: compliance_main_prompt.txt
      volumes:
        - name: elasticsearch-index-config
          configMap:
            # Ensure this ConfigMap exists or is created by the chart
            name: elasticsearch-index-config
        - name: inventory-data-config
          configMap:
            # Ensure this ConfigMap exists or is created by the chart
            name: inventory-data-config
        - name: migrator-config
          configMap:
            # This ConfigMap is defined elsewhere (e.g., migrator-configmap.yaml)
            name: migrator-config
  backoffLimit: 10 # Number of retries for the job
---
# Keep the ConfigMap definitions below as they were

apiVersion: v1
kind: ConfigMap
metadata:
  name: migrator-config
  namespace: {{ .Release.Namespace }}
data:
  metadata.json: |
    [
      {"key": "workspace_date_time_format", "type": "string", "value": "1900-01-02"},
      {"key": "workspace_debug_mode", "type": "bool", "value": "FALSE"},
      {"key": "workspace_time_window", "type": "string", "value": "30d"},
      {"key": "asset_management_enabled", "type": "bool", "value": "TRUE"},
      {"key": "compliance_enabled", "type": "bool", "value": "TRUE"},
      {"key": "product_management_enabled", "type": "bool", "value": "TRUE"},
      {"key": "allow_invite", "type": "bool", "value": "TRUE"},
      {"key": "workspace_key_support", "type": "bool", "value": "TRUE"},
      {"key": "workspace_max_keys", "type": "int", "value": "3"},
      {"key": "allowed_email_domains", "type": "string", "value": ""},
      {"key": "auto_discovery_method", "type": "string", "value": "scheduled"},
      {"key": "full_discovery_job_interval", "type": "int", "value": "48"},
      {"key": "cost_discovery_job_interval", "type": "int", "value": "24"},
      {"key": "describe_job_interval", "type": "int", "value": "8"},
      {"key": "health_check_job_interval", "type": "int", "value": "60"},
      {"key": "insight_job_interval", "type": "int", "value": "2"},
      {"key": "metrics_job_interval", "type": "int", "value": "2"},
      {"key": "compliance_job_interval", "type": "int", "value": "24"},
      {"key": "data_retention_duration", "type": "int", "value": "366"},
      {"key": "connection_limit", "type": "int", "value": "1000"},
      {"key": "user_limit", "type": "int", "value": "1000"},
      {"key": "analytics_git_url", "type": "string", "value": "https://github.com/opengovern/platform-configuration"},
      {"key": "asset_discovery_aws_policy_arns", "type": "string", "value": "arn:aws:iam::aws:policy/SecurityAudit,arn:aws:iam::aws:policy/ReadOnlyAccess"},
      {"key": "spend_discovery_aws_policy_arns", "type": "string", "value": "arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess"},
      {"key": "asset_discovery_azure_role_ids", "type": "string", "value": "/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7"},
      {"key": "spend_discovery_azure_role_ids", "type": "string", "value": "/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/fa23ad8b-c56e-40d8-ac0c-ce449e1d2c64"},
      # Duplicated key below? Verify if intended.
      # {"key": "spend_discovery_azure_role_ids", "type": "string", "value": "/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/fa23ad8b-c56e-40d8-ac0c-ce449e1d2c64"},
      {"key": "aws_discovery_required_only", "type": "bool", "value": "true"},
      {"key": "azure_discovery_required_only", "type": "bool", "value": "true"},
      {"key": "asset_discovery_enabled", "type": "bool", "value": "true"},
      {"key": "spend_discovery_enabled", "type": "bool", "value": "true"},
      {"key": "customization_enabled", "type": "bool", "value": "true"}
    ]
  # Placeholder prompts
  chat_prompt.txt: |
    Prompt
  main_prompt.txt: |
    Prompt
  assets_chat_prompt.txt: |
    Prompt
  assets_main_prompt.txt: |
    Prompt
  score_chat_prompt.txt: |
    TODO
  score_main_prompt.txt: |
    Prompt
  compliance_chat_prompt.txt: |
    Prompt
  compliance_main_prompt.txt: |
    Prompt
  # Added query_parameters.json based on volumeMount
  query_parameters.json: |
    {} # Add default content if needed
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-data-config
  namespace: {{ .Release.Namespace }}
data:
  # This requires an 'inventory-data/' directory at the chart root
  # containing files to be included here.
  {{- (.Files.Glob "inventory-data/*").AsConfig | nindent 2 }}
