apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configuration-access
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "keda.sh/v1alpha1"
    resources:
      - "scaledobjects"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - "keda.sh"
    resources:
      - "scaledobjects"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "deletecollection"
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configuration-access
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: configuration
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: configuration-access
  apiGroup: rbac.authorization.k8s.io
