apiVersion: v1
kind: Service
metadata:
  name: compliance-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: compliance-service
    service-monitor: {{ .Release.Name }}
spec:
  selector:
    app: compliance-service
  ports:
  - name: http
    port: 7251
    targetPort: 7251