apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:

      containers:
      - name: ui
        image: "{{ .Values.opengovernance.docker.registry }}/web-ui:{{ .Values.opengovernance.docker.tags.ui }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 7298
        envFrom:
          - configMapRef:
              name: ui-env
        volumeMounts:
          - mountPath: /usr/share/nginx/html/.env
            name: ui-env
            subPath: .env
      volumes:
        - name: ui-env
          configMap:
            name: ui-env
            items:
              - key: .env
                path: .env

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: ui
data:
  .env: |
    NODE_ENV=production
    REACT_APP_NODE_ENV=prod
    REACT_APP_MUI_LICENSE={{ .Values.opengovernance.ui.muiLicense }}
    REACT_APP_DOMAIN: "https://{{ .Values.global.domain }}"
    REACT_APP_BASE_URL="https://{{ .Values.global.domain }}"
    REACT_APP_AUTH_BASE_URL="https://{{ .Values.global.domain }}"
  NODE_ENV: production
  REACT_APP_NODE_ENV: prod
  REACT_APP_MUI_LICENSE: {{ .Values.opengovernance.ui.muiLicense }}
  REACT_APP_DOMAIN: "https://{{ .Values.global.domain }}"
  REACT_APP_BASE_URL: "https://{{ .Values.global.domain }}"
  REACT_APP_AUTH_BASE_URL: "https://{{ .Values.global.domain }}"
