---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-migrator
---
apiVersion: v1
kind: Secret
metadata:
  name: migrator-secret
  annotations:
    kubernetes.io/service-account.name: migrator
type: kubernetes.io/service-account-token
