---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-install
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-post-install
---
apiVersion: v1
kind: Secret
metadata:
  name: post-install-secret
  annotations:
    kubernetes.io/service-account.name: post-install
type: kubernetes.io/service-account-token
