apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: integration-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      serviceAccountName: integration
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: opencomply-node
                    operator: In
                    values:
                      - app
      containers:
      - name: integration-service
        image: "{{ .Values.opengovernance.docker.registry }}/integration:{{ .Values.opengovernance.docker.tags.integration }}"
        command: ["/integration-service"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 4000Mi
          requests:
            cpu: 100m
            memory: 2000Mi
        env:
        - name: INTEGRATION_POSTGRES__HOST
          value: "{{ include "postgres.endpoint" . }}"
        - name: INTEGRATION_POSTGRES__PORT
          value: "{{ include "postgres.port" . }}"
        - name: INTEGRATION_POSTGRES__DB
          value: "integration"
        - name: INTEGRATION_POSTGRES__USERNAME
          value: "postgres"
        - name: INTEGRATION_POSTGRES__PASSWORD
          value: "postgres"
        - name: INTEGRATION_POSTGRES__SSLMODE
          value: "{{ include "postgres.sslMode" . }}"
        - name: INTEGRATION_HTTP__ADDRESS
          value: "0.0.0.0:8000"
        - name: INTEGRATION_DESCRIBE__BASE_URL
          value: "http://scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251"
        - name: INTEGRATION_CORE__BASE_URL
          value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251"

        - name: INTEGRATION_STEAMPIPE__HOST
          value: cloudql-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: INTEGRATION_STEAMPIPE__PORT
          value: "9193"
        - name: INTEGRATION_STEAMPIPE__USERNAME
          value: "steampipe"
        - name: INTEGRATION_STEAMPIPE__PASSWORD
          value: "abcd"
        - name: INTEGRATION_STEAMPIPE__DB
          value: "steampipe"
        - name: INTEGRATION_VAULT__PROVIDER
          value: "hashicorp-vault"
        - name: INTEGRATION_VAULT__HASHICORP__ADDRESS
          value: "http://{{ .Release.Name }}-vault-internal.{{.Release.Namespace}}.svc.cluster.local:8200"
        - name: INTEGRATION_VAULT__KEY_ID
          value: {{ .Values.opengovernance.vault.keyID }}
        - name: INTEGRATION_MASTER_ACCESS_KEY
          value: ""
        - name: INTEGRATION_MASTER_SECRET_KEY
          value: ""
        - name: INTEGRATION_JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: INTEGRATION_JAEGER_SERVICE_NAME
          value: "integration-service"
        - name: INTEGRATION_JAEGER_SAMPLE_RATE
          value: "0.005"

{{- include "elastic.envs" . | indent 8 }}
        - name: CURRENT_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: KEDA_ENABLED
          value: "{{ .Values.keda.enabled }}"
        - name: NATS_URL
          value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
        - name: SCALED_OBJECT_NATS_URL
          value: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"