apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: integration-service
    service-monitor: {{ .Release.Name }}
spec:
  selector:
    app: integration-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000