---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: integration-secret
  annotations:
    kubernetes.io/service-account.name: integration
type: kubernetes.io/service-account-token