---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
---
apiVersion: v1
kind: Secret
metadata:
  name: scheduler-secret
  annotations:
    kubernetes.io/service-account.name: scheduler
type: kubernetes.io/service-account-token
