apiVersion: v1
kind: ConfigMap
metadata:
  name: steampipe-service-config
  namespace: {{ .Release.Namespace }}
data:
  aws.spc: |
    connection "aws" {
      plugin = "aws"
      addresses = []
      username = ""
      password = ""
    }

  azure.spc: |
    connection "azure" {
      plugin = "azure"
      addresses = []
      username = ""
      password = ""
    }

  azuread.spc: |
    connection "azuread" {
      plugin = "azuread"
      addresses = []
      username = ""
      password = ""
    }

  kaytu.spc: |
    connection "kaytu" {
      plugin = "local/kaytu"
      addresses = []
      username = ""
      password = ""
      pg_host = "{{ include "postgres.endpoint" . }}"
      pg_port = "{{ include "postgres.port" . }}"
      pg_user = "steampipe_user"
      pg_password = ""
      pg_database = "onboard"
      pg_ssl_mode = "{{ include "postgres.sslMode" . }}"
      pennywise_baseurl = "http://pennywise-server-service.{{ .Release.Namespace }}.svc.cluster.local:8080"
      compliance_service_baseurl = "http://compliance-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
    }
