apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-init-data-config
  namespace: {{ .Release.Namespace }}
data:
  {{- $files := .Files.Glob "migrator-data/bak-files/*" }}
 {{- range $path, $file := $files }}
  {{ base $path }}: |-
    {{ $files.Get $path | b64enc }}
  {{- end }}