---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core
---
apiVersion: v1
kind: Secret
metadata:
  name: core-secret
  annotations:
    kubernetes.io/service-account.name: core
type: kubernetes.io/service-account-token
