{{- if eq .Values.keda.enabled true }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-worker-scaled-object
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-worker
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 3
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "analytics-worker"
        consumer: "analytics-worker-service"
        lagThreshold: "10"
        useHttps: "false"
---
{{- end }}