{{- if eq .Values.opensecurity.compliance true }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance
---
apiVersion: v1
kind: Secret
metadata:
  name: compliance-secret
  annotations:
    kubernetes.io/service-account.name: compliance
type: kubernetes.io/service-account-token
{{- end }}