# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: auth-service
#   namespace: {{ .Release.Namespace }}
# spec:
#   # Secret names are always required.
#   secretName: auth-service-tls
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   subject:
#     organizations:
#       - kaytu
#   commonName: auth-service
#   isCA: false
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   usages:
#     - server auth
#     - client auth
#   dnsNames:
#     - auth-service
#     - auth-service.{{ .Release.Namespace }}.svc.cluster.local
#   # Issuer references are always required.
#   issuerRef:
#     name: namespace-issuer
#     # We can reference ClusterIssuers by changing the kind here.
#     # The default value is Issuer (i.e. a locally namespaced Issuer)
#     kind: Issuer
#     # This is optional since cert-manager will default to this value however
#     # if you are using an external issuer, change this to that issuer group.
#     group: cert-manager.io