# /Users/anil/workspace/charts/opensecurity/charts/dex/templates/deployment.yaml
# MODIFIED to include an initContainer to wait for PostgreSQL readiness.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
    {{ with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{ with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.configSecret.create }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "dex.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dex.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: wait-for-postgres-dex
          image: postgres:15.5
          env:
            {{- with .Values.dexDatabase }}
            - name: PGHOST
              value: {{ .hostName | default (printf "%s-postgresql-primary.%s.svc.cluster.local." $.Release.Name $.Release.Namespace) | quote }}
            - name: PGPORT
              value: {{ .port       | default "5432" | quote }}
            - name: PGDATABASE
              value: {{ .name       | default "dex"  | quote }}
            - name: PGUSER
              value: {{ .username   | default "dex_service" | quote }}
            - name: PGSSLMODE
              value: {{ .sslMode    | default "disable"    | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .passwordSecretName | default "postgres-secret"             | quote }}
                  key:  {{ .passwordSecretKey  | default "dexServiceUserPassword" | quote }}
            {{- else }}
            - name: PGHOST
              value: {{ printf "%s-postgresql-primary.%s.svc.cluster.local." $.Release.Name $.Release.Namespace | quote }}
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "dex"
            - name: PGUSER
              value: "dex_service"
            - name: PGSSLMODE
              value: "disable"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-secret"
                  key:  "dexServiceUserPassword"
            {{- end }}
          command: ["sh", "-xc"]
          args:
            - |
              echo "Waiting for PostgreSQL at ${PGHOST}:${PGPORT} db=${PGDATABASE} user=${PGUSER} (sslmode=${PGSSLMODE})…"
              retries=30; delay=5; count=0
              until pg_isready \
                -h "${PGHOST}" \
                -p "${PGPORT}" \
                -U "${PGUSER}" \
                -d "${PGDATABASE}" \
                -q -t 2; do
                count=$((count+1))
                if [ "$count" -ge "$retries" ]; then
                  echo "PostgreSQL unavailable after ${retries} retries – exiting."
                  exit 1
                fi
                echo "…sleep ${delay}s (attempt ${count}/${retries})"
                sleep "${delay}"
              done
              echo "PostgreSQL is ready!"
          resources:
            limits:
              cpu:    "150m"
              memory: "128Mi"
            requests:
              cpu:    "50m"
              memory: "64Mi"
      # ===== END Wait for PostgreSQL Init Container =====






      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - dex
            - serve
            - --web-http-addr
            - 0.0.0.0:5556
            {{- if .Values.https.enabled }}
            - --web-https-addr
            - 0.0.0.0:5554
            {{- end }}
            {{- if .Values.grpc.enabled }}
            - --grpc-addr
            - 0.0.0.0:5557
            {{- end }}
            - --telemetry-addr
            - 0.0.0.0:5558
            - /etc/dex/config.yaml
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.envVars }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 5556
              protocol: TCP
            {{- if .Values.https.enabled }}
            - name: https
              containerPort: 5554
              protocol: TCP
            {{- end }}
            {{- if .Values.grpc.enabled }}
            - name: grpc
              containerPort: 5557
              protocol: TCP
            {{- end }}
            - name: telemetry
              containerPort: 5558
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: telemetry
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: telemetry
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/dex
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "dex.configSecretName" . }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}