apiVersion: v1
kind: Service
metadata:
  name: frontend-v2-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend-v2
spec:
  selector:
    app: frontend-v2
  ports:
  - port: 7298
    targetPort: 7298