apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-service
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.opengovernance.vault.aws.roleArn }}
---
apiVersion: v1
kind: Secret
metadata:
  name: workspace-service-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: workspace-service
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: workspace-service
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: workspace-service
  template:
    metadata:
      labels:
        app: workspace-service
    spec:
      serviceAccountName: workspace-service

      containers:
        - name: workspace-service
          image: "{{ .Values.opengovernance.docker.registry }}/workspace-service:{{ .Values.opengovernance.docker.tags.workspace }}"
          command: [ "/workspace-service" ]
          imagePullPolicy: Always
          env:
            - name: WORKSPACE_POSTGRES__HOST
              value: "{{ include "postgres.endpoint" . }}"
            - name: WORKSPACE_POSTGRES__PORT
              value: "{{ include "postgres.port" . }}"
            - name: WORKSPACE_POSTGRES__DB
              value: "workspace"
            - name: WORKSPACE_POSTGRES__USERNAME
              value: "workspace_service"
            - name: WORKSPACE_POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: workspaceServiceUserPassword
            - name: WORKSPACE_POSTGRES_SSL_MODE
              value: "{{ include "postgres.sslMode" . }}"
            - name: WORKSPACE_HTTP__ADDRESS
              value: "0.0.0.0:8351"
            - name: WORKSPACE_DOMAIN_SUFFIX
              value: "{{ .Values.global.domain }}"
            - name: WORKSPACE_APP_DOMAIN
              value: "{{ .Values.global.domain }}"
            - name: WORKSPACE_AUTH__BASE_URL
              value: "http://auth-service.{{ .Release.Namespace }}.svc.cluster.local:8251"
            - name: WORKSPACE_ONBOARD__BASE_URL
              value: "http://onboard-service.%NAMESPACE%.svc.cluster.local:6251"
            - name: WORKSPACE_SCHEDULER__BASE_URL
              value: "http://describe-scheduler.%NAMESPACE%.svc.cluster.local:5251"
            - name: WORKSPACE_COMPLIANCE__BASE_URL
              value: "http://compliance-service.%NAMESPACE%.svc.cluster.local:7251"
            - name: WORKSPACE_INVENTORY__BASE_URL
              value: "http://inventory-service.%NAMESPACE%.svc.cluster.local:7251"
            - name: WORKSPACE_METADATA__BASE_URL
              value: "http://metadata-service.%NAMESPACE%.svc.cluster.local:6251"
            - name: WORKSPACE_AUTO_SUSPEND_DURATION_MINUTES
              value: "60"
            - name: WORKSPACE_KAYTU_HELM_CHART_LOCATION
              value: "{{ .Values.opengovernance.workspace.kaytuChartLocation }}"
            - name: WORKSPACE_KAYTU_OCTOPUS_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: WORKSPACE_PRIMARY_DOMAIN_URL
              value: "{{ .Values.global.domain }}"
            - name: WORKSPACE_FLUX_SYSTEM_NAMESPACE
              value: "{{ .Values.flux.namespace }}"
            - name: WORKSPACE_VAULT__PROVIDER
              value: {{ .Values.opengovernance.vault.provider }}
            - name: WORKSPACE_VAULT__AWS__REGION
              value: {{ .Values.opengovernance.vault.aws.region }}
            - name: WORKSPACE_VAULT__AWS__ROLE_ARN
              value: {{ .Values.opengovernance.vault.aws.roleArn }}
            - name: WORKSPACE_VAULT__AWS__ACCESS_KEY
              value: {{ .Values.opengovernance.vault.aws.accessKey }}
            - name: WORKSPACE_VAULT__AWS__SECRET_KEY
              value: {{ .Values.opengovernance.vault.aws.secretKey }}
            - name: WORKSPACE_VAULT__AZURE__BASE_URL
              value: {{ .Values.opengovernance.vault.azure.baseUrl }}
            - name: WORKSPACE_VAULT__AZURE__CLIENT_ID
              value: {{ .Values.opengovernance.vault.azure.clientId }}
            - name: WORKSPACE_VAULT__AZURE__TENANT_ID
              value: {{ .Values.opengovernance.vault.azure.tenantId }}
            - name: WORKSPACE_VAULT__AZURE__CLIENT_SECRET
              value: {{ .Values.opengovernance.vault.azure.clientSecret }}
            - name: WORKSPACE_VAULT__HASHICORP__ADDRESS
              value: "http://{{ .Release.Name }}-vault-internal.{{ .Release.Namespace }}.svc.cluster.local:8200"
            - name: WORKSPACE_VAULT__KEY_ID
              value: {{ .Values.opengovernance.vault.keyID }}
            - name: WORKSPACE_DEX_GRPC_ADDR
              value: "opengovernance-dex.{{ .Release.Namespace }}.svc.cluster.local:5557"


            - name: WORKSPACE_AWS_MASTER_POLICY_ARN
              value: "{{ .Values.opengovernance.master.policyARN }}"
            - name: WORKSPACE_OPEN_SEARCH_REGION
              value: "us-east-2"
            - name: WORKSPACE_AWS_ACCOUNT_ID
              value: "{{ .Values.opengovernance.master.accountID }}"
            - name: WORKSPACE_OIDC_PROVIDER
              value: "{{ .Values.opengovernance.master.oidcProvider }}"
            - name: WORKSPACE_MASTER_ROLE_ARN
              value: "{{ .Values.opengovernance.master.masterRoleARN }}"
            - name: WORKSPACE_SECURITY_GROUP_ID
              value: "{{ .Values.opengovernance.master.securityGroupID }}"
            - name: WORKSPACE_SUBNET_ID
              value: "{{ .Values.opengovernance.master.subnetID }}"
            - name: WORKSPACE_DO_RESERVE
              value: "false"
            - name: WORKSPACE_KAYTU_WORKSPACE_VERSION
              value: "{{ .Values.opengovernance.workspace.chart.version }}"
            - name: WORKSPACE_SAMPLEDATA_INTEGRATIONS_CHECK
              value: "79302008-5d35-4a83-914c-20ecd80f4228,e6cb0afa-e624-4ca7-8b47-fa9988831137,1c2a6b18-ac87-4f5e-a472-1e26f8704f29,c00bb650-f448-41b7-8ccc-bcd6184f78c3"
