apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: workspace-service
    monitoring: kaytu
spec:
  selector:
    app: workspace-service
  ports:
    - name: http
      protocol: TCP
      port: 8351
      targetPort: 8351
