---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configuration
---
apiVersion: v1
kind: Secret
metadata:
  name: configuration-secret
  annotations:
    kubernetes.io/service-account.name: configuration
type: kubernetes.io/service-account-token
