apiVersion: v1
kind: ServiceAccount
metadata:
  name: og-describer-digitalocean
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: og-describer-digitalocean
  namespace: {{ .Release.Namespace }}
  labels:
    app: og-describer-digitalocean
spec:
  minReadySeconds: 10
  {{- if eq .Values.keda.enabled true }}
  replicas: 0
  {{- else }}
  replicas: 5
  {{- end }}
  selector:
    matchLabels:
      app: og-describer-digitalocean
  template:
    metadata:
      labels:
        app: og-describer-digitalocean
    spec:
      serviceAccountName: og-describer-digitalocean
      containers:
        - name: og-describer-digitalocean
          image: "{{ .Values.opengovernance.docker.registry }}/og-describer-digitalocean:{{ .Values.opengovernance.docker.tags.describeWorkerDigitalocean }}"
          command: ["/og-describer-digitalocean"]
          imagePullPolicy: Always
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 1Gi
          #  requests:
          #    cpu: 100m
          #    memory: 300Mi
          env:
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: og-describer-digitalocean-manuals
  namespace: {{ .Release.Namespace }}
  labels:
    app: og-describer-digitalocean-manuals
spec:
  minReadySeconds: 10
  {{- if eq .Values.keda.enabled true }}
  replicas: 0
  {{- else }}
  replicas: 2
  {{- end }}
  selector:
    matchLabels:
      app: og-describer-digitalocean-manuals
  template:
    metadata:
      labels:
        app: og-describer-digitalocean-manuals
    spec:
      serviceAccountName: og-describer-digitalocean
      containers:
        - name: og-describer-digitalocean
          image: "{{ .Values.opengovernance.docker.registry }}/og-describer-digitalocean:{{ .Values.opengovernance.docker.tags.describeWorkerDigitalocean }}"
          command: ["/og-describer-digitalocean"]
          imagePullPolicy: Always
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 1Gi
          #  requests:
          #    cpu: 100m
          #    memory: 300Mi
          env:
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
            - name: MANUAL_TRIGGERS
              value: "true"