apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: task-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opensecurity.replicaCount }}
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      serviceAccountName: task
      containers:
      - name: task-service
        image: "{{ .Values.opensecurity.docker.registry }}/task-service:{{ .Values.opensecurity.docker.tags.tasks }}"
        command: ["/task-service"]
        imagePullPolicy: Always
        env:
        - name: TASKS_POSTGRES__HOST
          value: "{{ include "postgres.endpoint" . }}"
        - name: TASKS_POSTGRES__PORT
          value: "{{ include "postgres.port" . }}"
        - name: TASKS_POSTGRES__DB
          value: "task"
        - name: TASKS_POSTGRES__USERNAME
          value: "postgres"
        - name: TASKS_POSTGRES__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: TASKS_POSTGRES__SSLMODE
          value: "{{ include "postgres.sslMode" . }}"
        - name: TASKS_HTTP__ADDRESS
          value: "0.0.0.0:8001"
        - name: TASKS_CORE__BASE_URL
          value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
        - name: TASKS_VAULT__PROVIDER
          value: "hashicorp-vault"
        - name: TASKS_VAULT__HASHICORP__ADDRESS
          value: "http://{{ .Release.Name }}-vault-internal.{{.Release.Namespace}}.svc.cluster.local:8200"
        - name: TASKS_VAULT__KEY_ID
          value: {{ .Values.opensecurity.vault.keyID }}

{{- include "elastic.envs" . | indent 8 }}

        - name: TASKS_ESSINK_ENDPOINT
          value: "es-sink-service.{{ .Release.Namespace }}.svc.cluster.local:5252"

        - name: CURRENT_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: KEDA_ENABLED
          value: "{{ .Values.keda.enabled }}"
        - name: TASKS_NATS__URL
          value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
        - name: SCALED_OBJECT_NATS_URL
          value: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        - name: CORE_BASEURL
          value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
        - name: NATS_URL
          value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"