---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task
---
apiVersion: v1
kind: Secret
metadata:
  name: task-secret
  annotations:
    kubernetes.io/service-account.name: task
type: kubernetes.io/service-account-token