{{- if eq .Values.keda.enabled true }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: og-describer-entraid-scaled-object
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: og-describer-entraid
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 1
  maxReplicaCount: 20
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "og_describer_entraid"
        consumer: "describer-entraid-service"
        lagThreshold: "20"
        useHttps: "false"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: og-describer-entraid-manuals-scaled-object
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: og-describer-entraid-manuals
  pollingInterval: 5
  cooldownPeriod:  300
  minReplicaCount: 1
  maxReplicaCount: 20
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "og_describer_entraid"
        consumer: "describer-entraid-manuals-service"
        lagThreshold: "20"
        useHttps: "false"
---
{{- end }}